export const SYSTEM_ERRORS = {
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
	INVALID_UUID: 'INVALID_UUID',
	UNAUTHORIZED: 'UNAUTHORIZED',
} as const;
