export const TRANSACTION_ERROR = {
	INVALID_DATE: 'INVALID_DATE',
	INVALID_AMOUNT: 'INVALID_AMOUNT',
	INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
	AMOUNT_VERY_LARGE: 'AMOUNT_VERY_LARGE',
	AMOUNT_VERY_LOW: 'AMOUNT_VERY_LOW',
} as const;
