export const USER_ERRORS = {
	INVALID_NAME: 'INVALID_NAME',
	NAME_VERY_SHORT: 'NAME_VERY_SHORT',
	NAME_VERY_LONG: 'NAME_VERY_LONG',
	INVALID_EMAIL: 'INVALID_EMAIL',
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	PASSWORD_VERY_SHORT: 'PASSWORD_VERY_SHORT',
	PASSWORD_VERY_LONG: 'PASSWORD_VERY_LONG',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
	PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
} as const;
