name: Deploy

on:
  push:
    branches:
      - main

jobs:
  pre:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Make main envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SERVER_ENV: ${{ secrets.SERVER_ENV }}
          envkey_SERVER_PORT: ${{ secrets.SERVER_PORT }}
          envkey_SERVER_HOST: ${{ secrets.SERVER_HOST }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false

  check:
    needs: pre
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.5.0'

      - name: Install dependences
        run: npm ci --include=dev

      - name: ESlint
        run: npm run eslint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Make test envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SERVER_ENV: ${{ secrets.SERVER_ENV }}
          envkey_SERVER_PORT: ${{ secrets.SERVER_PORT }}
          envkey_SERVER_HOST: ${{ secrets.SERVER_HOST }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          file_name: .env.test
          fail_on_empty: false
          sort_keys: false

      - name: Start Database for Test
        run: docker compose -f docker-compose.test.yml up -d

      - name: Create Database
        run: npm run db:test:push

      - name: Test
        run: npm run test
