name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.5.0'

      - name: Install dependences
        run: npm ci --include=dev

      - name: ESlint
        run: npm run eslint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Criar arquivo .env
        run: |
          touch .env.test
          echo "SERVER_ENV=${{ secrets.SERVER_ENV }}" >> .env.test
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env.test
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env.test
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test

      - name: Start Database for Test
        run: docker compose -f docker-compose.test.yml up -d

      - name: Create Database
        run: npm run db:test:push

      - name: Test
        run: npm run test
